---
title: Exceções e manipulação de exceções – Guia de Programação em C#
description: Saiba mais sobre exceções e tratamento de exceções. Esses recursos do C# ajudam a lidar com situações inesperadas ou excepcionais que ocorrem quando um programa está em execução.
ms.date: 12/09/2020
helpviewer_keywords:
- exception handling [C#]
- exceptions [C#]
- C# language, exceptions
ms.assetid: 0001887f-4fa2-47e2-8034-2819477e2344
ms.openlocfilehash: 679171e6d397741ef44cb37fb770f6feba039fd9
ms.sourcegitcommit: 9b877e160c326577e8aa5ead22a937110d80fa44
ms.translationtype: MT
ms.contentlocale: pt-BR
ms.lasthandoff: 12/11/2020
ms.locfileid: "97110618"
---
# <a name="exceptions-and-exception-handling-c-programming-guide"></a><span data-ttu-id="1e4d1-104">Exceções e manipulação de exceções (Guia de Programação em C#)</span><span class="sxs-lookup"><span data-stu-id="1e4d1-104">Exceptions and Exception Handling (C# Programming Guide)</span></span>

<span data-ttu-id="1e4d1-105">Os recursos de manipulação de exceção da linguagem C# ajudam você a lidar com quaisquer situações excepcionais ou inesperadas que ocorram quando um programa for executado.</span><span class="sxs-lookup"><span data-stu-id="1e4d1-105">The C# language's exception handling features help you deal with any unexpected or exceptional situations that occur when a program is running.</span></span> <span data-ttu-id="1e4d1-106">A manipulação de exceções usa as `try` `catch` `finally` palavras-chave, e para testar as ações que podem não ter sucesso, para lidar com falhas quando você decide que é razoável fazê-lo e para limpar os recursos posteriormente.</span><span class="sxs-lookup"><span data-stu-id="1e4d1-106">Exception handling uses the `try`, `catch`, and `finally` keywords to try actions that may not succeed, to handle failures when you decide that it's reasonable to do so, and to clean up resources afterward.</span></span> <span data-ttu-id="1e4d1-107">As exceções podem ser geradas pelo Common Language Runtime (CLR), por bibliotecas .NET ou de terceiros, ou por código de aplicativo.</span><span class="sxs-lookup"><span data-stu-id="1e4d1-107">Exceptions can be generated by the common language runtime (CLR), by .NET or third-party libraries, or by application code.</span></span> <span data-ttu-id="1e4d1-108">As exceções são criadas usando a palavra-chave `throw`.</span><span class="sxs-lookup"><span data-stu-id="1e4d1-108">Exceptions are created by using the `throw` keyword.</span></span>

<span data-ttu-id="1e4d1-109">Em muitos casos, uma exceção pode ser lançada não por um método que seu código chamou diretamente, mas por outro método mais abaixo na pilha de chamadas.</span><span class="sxs-lookup"><span data-stu-id="1e4d1-109">In many cases, an exception may be thrown not by a method that your code has called directly, but by another method further down in the call stack.</span></span> <span data-ttu-id="1e4d1-110">Quando uma exceção é gerada, o CLR desenrolará a pilha, procurando um método com um `catch` bloco para o tipo de exceção específico e executará o primeiro `catch` bloco desse bloqueio que, se encontrar.</span><span class="sxs-lookup"><span data-stu-id="1e4d1-110">When an exception is thrown happens, the CLR will unwind the stack, looking for a method with a `catch` block for the specific exception type, and it will execute the first such `catch` block that if finds.</span></span> <span data-ttu-id="1e4d1-111">Se ele não encontrar um bloco `catch` apropriado na pilha de chamadas, ele encerrará o processo e exibirá uma mensagem para o usuário.</span><span class="sxs-lookup"><span data-stu-id="1e4d1-111">If it finds no appropriate `catch` block anywhere in the call stack, it will terminate the process and display a message to the user.</span></span>

<span data-ttu-id="1e4d1-112">Neste exemplo, um método testa a divisão por zero e captura o erro.</span><span class="sxs-lookup"><span data-stu-id="1e4d1-112">In this example, a method tests for division by zero and catches the error.</span></span> <span data-ttu-id="1e4d1-113">Sem a manipulação de exceção, esse programa encerraria com um **DivideByZeroException não resolvido**.</span><span class="sxs-lookup"><span data-stu-id="1e4d1-113">Without the exception handling, this program would terminate with a **DivideByZeroException was unhandled** error.</span></span>

:::code language="csharp" source="snippets/exceptions/ExceptionTest.cs" ID="ExceptionTest":::

## <a name="exceptions-overview"></a><span data-ttu-id="1e4d1-114">Visão geral sobre exceções</span><span class="sxs-lookup"><span data-stu-id="1e4d1-114">Exceptions Overview</span></span>

<span data-ttu-id="1e4d1-115">As exceções têm as seguintes propriedades:</span><span class="sxs-lookup"><span data-stu-id="1e4d1-115">Exceptions have the following properties:</span></span>

- <span data-ttu-id="1e4d1-116">As exceções são tipos que derivam, por fim, de `System.Exception`.</span><span class="sxs-lookup"><span data-stu-id="1e4d1-116">Exceptions are types that all ultimately derive from `System.Exception`.</span></span>
- <span data-ttu-id="1e4d1-117">Use um bloco `try` nas instruções que podem lançar exceções.</span><span class="sxs-lookup"><span data-stu-id="1e4d1-117">Use a `try` block around the statements that might throw exceptions.</span></span>
- <span data-ttu-id="1e4d1-118">Quando ocorre uma exceção no bloco `try`, o fluxo de controle vai para o primeiro manipulador de exceção associada que está presente em qualquer lugar na pilha de chamadas.</span><span class="sxs-lookup"><span data-stu-id="1e4d1-118">Once an exception occurs in the `try` block, the flow of control jumps to the first associated exception handler that is present anywhere in the call stack.</span></span> <span data-ttu-id="1e4d1-119">No C#, a palavra-chave `catch` é usada para definir um manipulador de exceção.</span><span class="sxs-lookup"><span data-stu-id="1e4d1-119">In C#, the `catch` keyword is used to define an exception handler.</span></span>
- <span data-ttu-id="1e4d1-120">Se nenhum manipulador de exceção para uma determinada exceção estiver presente, o programa interromperá a execução com uma mensagem de erro.</span><span class="sxs-lookup"><span data-stu-id="1e4d1-120">If no exception handler for a given exception is present, the program stops executing with an error message.</span></span>
- <span data-ttu-id="1e4d1-121">Não Capture uma exceção, a menos que você possa tratá-la e deixar o aplicativo em um estado conhecido.</span><span class="sxs-lookup"><span data-stu-id="1e4d1-121">Don't catch an exception unless you can handle it and leave the application in a known state.</span></span> <span data-ttu-id="1e4d1-122">Se você capturar `System.Exception`, relance-o usando a palavra-chave `throw` no final do bloco `catch`.</span><span class="sxs-lookup"><span data-stu-id="1e4d1-122">If you catch `System.Exception`, rethrow it using the `throw` keyword at the end of the `catch` block.</span></span>
- <span data-ttu-id="1e4d1-123">Se um bloco `catch` define uma variável de exceção, você pode usá-lo para obter mais informações sobre o tipo de exceção que ocorreu.</span><span class="sxs-lookup"><span data-stu-id="1e4d1-123">If a `catch` block defines an exception variable, you can use it to obtain more information about the type of exception that occurred.</span></span>
- <span data-ttu-id="1e4d1-124">As exceções podem ser geradas explicitamente por um programa usando a palavra-chave `throw`.</span><span class="sxs-lookup"><span data-stu-id="1e4d1-124">Exceptions can be explicitly generated by a program by using the `throw` keyword.</span></span>
- <span data-ttu-id="1e4d1-125">Os objetos de exceção contêm informações detalhadas sobre o erro, como o estado da pilha de chamadas e uma descrição de texto do erro.</span><span class="sxs-lookup"><span data-stu-id="1e4d1-125">Exception objects contain detailed information about the error, such as the state of the call stack and a text description of the error.</span></span>
- <span data-ttu-id="1e4d1-126">O código em um bloco `finally` será executado mesmo se uma exceção for lançada.</span><span class="sxs-lookup"><span data-stu-id="1e4d1-126">Code in a `finally` block is executed even if an exception is thrown.</span></span> <span data-ttu-id="1e4d1-127">Use um bloco `finally` para liberar recursos, por exemplo, para fechar todos os fluxos ou arquivos que foram abertos no bloco `try`.</span><span class="sxs-lookup"><span data-stu-id="1e4d1-127">Use a `finally` block to release resources, for example to close any streams or files that were opened in the `try` block.</span></span>
- <span data-ttu-id="1e4d1-128">As exceções gerenciadas no .NET são implementadas sobre o mecanismo de manipulação de exceção estruturada do Win32.</span><span class="sxs-lookup"><span data-stu-id="1e4d1-128">Managed exceptions in .NET are implemented on top of the Win32 structured exception handling mechanism.</span></span> <span data-ttu-id="1e4d1-129">Para obter mais informações, consulte [Manipulação de exceções estruturadas (C/C++)](/cpp/cpp/structured-exception-handling-c-cpp) e [Curso rápido sobre a manipulação de exceções estruturadas do Win32](http://bytepointer.com/resources/pietrek_crash_course_depths_of_win32_seh.htm).</span><span class="sxs-lookup"><span data-stu-id="1e4d1-129">For more information, see [Structured Exception Handling (C/C++)](/cpp/cpp/structured-exception-handling-c-cpp) and [A Crash Course on the Depths of Win32 Structured Exception Handling](http://bytepointer.com/resources/pietrek_crash_course_depths_of_win32_seh.htm).</span></span>

## <a name="c-language-specification"></a><span data-ttu-id="1e4d1-130">Especificação da Linguagem C#</span><span class="sxs-lookup"><span data-stu-id="1e4d1-130">C# Language Specification</span></span>

<span data-ttu-id="1e4d1-131">Para obter mais informações, veja [Exceções](~/_csharplang/spec/exceptions.md) na [Especificação da linguagem C#](/dotnet/csharp/language-reference/language-specification/introduction).</span><span class="sxs-lookup"><span data-stu-id="1e4d1-131">For more information, see [Exceptions](~/_csharplang/spec/exceptions.md) in the [C# Language Specification](/dotnet/csharp/language-reference/language-specification/introduction).</span></span> <span data-ttu-id="1e4d1-132">A especificação da linguagem é a fonte definitiva para a sintaxe e o uso de C#.</span><span class="sxs-lookup"><span data-stu-id="1e4d1-132">The language specification is the definitive source for C# syntax and usage.</span></span>

## <a name="see-also"></a><span data-ttu-id="1e4d1-133">Veja também</span><span class="sxs-lookup"><span data-stu-id="1e4d1-133">See also</span></span>

- <xref:System.SystemException>
- [<span data-ttu-id="1e4d1-134">Palavras-chave do C#</span><span class="sxs-lookup"><span data-stu-id="1e4d1-134">C# Keywords</span></span>](../../language-reference/keywords/index.md)
- [<span data-ttu-id="1e4d1-135">throw</span><span class="sxs-lookup"><span data-stu-id="1e4d1-135">throw</span></span>](../../language-reference/keywords/throw.md)
- [<span data-ttu-id="1e4d1-136">try-catch</span><span class="sxs-lookup"><span data-stu-id="1e4d1-136">try-catch</span></span>](../../language-reference/keywords/try-catch.md)
- [<span data-ttu-id="1e4d1-137">try-finally</span><span class="sxs-lookup"><span data-stu-id="1e4d1-137">try-finally</span></span>](../../language-reference/keywords/try-finally.md)
- [<span data-ttu-id="1e4d1-138">try-catch-finally</span><span class="sxs-lookup"><span data-stu-id="1e4d1-138">try-catch-finally</span></span>](../../language-reference/keywords/try-catch-finally.md)
- [<span data-ttu-id="1e4d1-139">Exceções</span><span class="sxs-lookup"><span data-stu-id="1e4d1-139">Exceptions</span></span>](../../../standard/exceptions/index.md)
